name: app_network
description: "Centralized Dio networking infrastructure, interceptors, and error mapping."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.6.0 <4.0.0'

resolution: workspace

dependencies:
  app_core: ^0.0.1
  dio: ^5.11.0

dev_dependencies:
  app_lints: ^0.0.1
  test: ^1.25.8
