name: app_network
description: "Centralized Dio networking infrastructure, interceptors, and error mapping."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  app_core: ^0.0.1
  dio: ^5.11.0
  logger: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  app_lints: ^0.0.1
