name: app_lints
description: "Shared linting and code quality configuration."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.6.0 <4.0.0'

resolution: workspace

dependencies:
  flutter_lints: ^6.0.0
