name: mobile
description: "Production-oriented Flutter Starter Application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.47.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # Architecture Shared Packages (Resolved natively via Pub Workspace)
  app_core: ^0.0.1
  app_network: ^0.0.1
  app_storage: ^0.0.1
  design_system: ^0.0.1
  auth_contract: ^0.0.1
  feature_auth: ^0.0.1

  # Routing
  kaisel: ^1.1.0

  # State Management
  bloc_signals: ^1.0.1
  signals_flutter: ^7.1.0

  # Models & DI
  get_it: ^9.2.1
  injectable: ^3.0.0

  # Networking & Utils
  dio: ^5.11.0
  toastification: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  app_lints: ^0.0.1

  build_runner: ^2.16.0
  flutter_native_splash: ^2.4.8
  injectable_generator: ^3.1.3

flutter:
  uses-material-design: true
