name: app_core
description: "Core abstractions, results, failures, exceptions, and logging."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.7.0
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  app_lints:
    path: ../app_lints
